"""Add is_in_stock column

Revision ID: 8cd905a447fa
Revises: 1fbfa43fdc29
Create Date: 2025-06-21 10:33:23.460611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd905a447fa'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plants', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plants', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('plants', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
